#pragma once

#define VENDOR_ID       0xFEED
#define PRODUCT_ID      0x0001
#define DEVICE_VER      0x0001
#define MANUFACTURER    "rrex_keypads"
#define PRODUCT         "rePad"

#define MATRIX_ROWS 1
#define MATRIX_COLS 3

#define ANALOG_PIN_0    GP28
#define ANALOG_PIN_1    GP27
#define ANALOG_PIN_2    GP26

#define ADC_RESOLUTION  12
#define ADC_SAMPLE_RATE 1000

#define KEY_0_ENABLED       1
#define KEY_1_ENABLED       1
#define KEY_2_ENABLED       1

#define TRAVEL_DISTANCE_IN_0_01MM   400

#define HE_ADC_DEFAULT_REST 2147
#define HE_ADC_DEFAULT_DOWN 3100

#define SENSOR_BOUNDARY_DEADZONE        10
#define SENSOR_BOUNDARY_MIN_DISTANCE    200

#define DEFAULT_ACTUATION_POINT     200
#define DEFAULT_RELEASE_POINT       180
#define DEFAULT_RT_DOWN             40
#define DEFAULT_RT_UP               40

#define HYSTERESIS_TOLERANCE                10
#define RAPID_TRIGGER_TOLERANCE             10
#define CONTINUOUS_RAPID_TRIGGER_THRESHOLD  10

#define RT_MIN_SENSITIVITY      5
#define RT_MAX_SENSITIVITY      200
#define RT_MIN_ACTUATION        20
#define RT_MAX_ACTUATION        380

#define WS2812_DI_PIN       GP0
#define RGB_MATRIX_LED_COUNT 3

#define RGB_PIN_0           GP29
#define RGB_PIN_1           GP16
#define RGB_PIN_2           GP0

#define WS2812_PIO_USE_PIO1
#define WS2812_TRST_US      280

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_DEFAULT_HUE  180
#define RGB_MATRIX_DEFAULT_SAT  255
#define RGB_MATRIX_DEFAULT_VAL  200
#define RGB_MATRIX_DEFAULT_SPD  100

#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH

#define RGB_MATRIX_LED_POSITIONS { \
    { 0,   32 }, \
    { 112, 32 }, \
    { 224, 32 }  \
}

#define RAW_USAGE_PAGE  0xFF60
#define RAW_USAGE_ID    0x61

#define EECONFIG_USER_DATA_SIZE 128
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define DEBOUNCE 0

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
